# Generated by Django 6.0.3 on 2026-03-24 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='prioridade',
            field=models.CharField(choices=[('NAO_URGENTE', 'Não urgente'), ('URGENTE', 'Urgente')], default='NAO_URGENTE', max_length=40),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='status',
            field=models.CharField(choices=[('ABERTA', 'Aberta'), ('EM_ANDAMENTO', 'Em andamento'), ('CONCLUIDA', 'Concluida'), ('CANCELADA', 'Cancelada')], default='ABERTA', max_length=20),
        ),
    ]
