# Generated by Django 6.0.3 on 2026-03-24 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0003_alter_tarefa_prioridade_alter_tarefa_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='status',
            field=models.CharField(choices=[('CONCLUIDA', 'Concluida'), ('EM_ANDAMENTO', 'Em andamento'), ('ABERTA', 'Aberta'), ('CANCELADA', 'Cancelada')], default='ABERTA', max_length=20),
        ),
    ]
