# Generated by Django 6.0.3 on 2026-03-24 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0004_alter_tarefa_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='prioridade',
            field=models.CharField(choices=[('NAO_URGENTE', 'Não urgente'), ('URGENTE', 'Urgente')], default='NAO_URGENTE', max_length=40),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='status',
            field=models.CharField(choices=[('CANCELADA', 'Cancelada'), ('CONCLUIDA', 'Concluida'), ('EM_ANDAMENTO', 'Em andamento'), ('ABERTA', 'Aberta')], default='ABERTA', max_length=20),
        ),
    ]
