# Generated by Django 6.0.3 on 2026-03-24 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0005_alter_tarefa_prioridade_alter_tarefa_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='status',
            field=models.CharField(choices=[('CANCELADA', 'Cancelada'), ('EM_ANDAMENTO', 'Em andamento'), ('ABERTA', 'Aberta'), ('CONCLUIDA', 'Concluida')], default='ABERTA', max_length=20),
        ),
    ]
