# Generated by Django 6.0.3 on 2026-04-06 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0006_alter_tarefa_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='prioridade',
            field=models.CharField(choices=[('URGENTE', 'Urgente'), ('NAO_URGENTE', 'Não urgente')], default='NAO_URGENTE', max_length=40),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='status',
            field=models.CharField(choices=[('ABERTA', 'Aberta'), ('CANCELADA', 'Cancelada'), ('CONCLUIDA', 'Concluida'), ('EM_ANDAMENTO', 'Em andamento')], default='ABERTA', max_length=20),
        ),
    ]
