# Generated by Django 6.0.3 on 2026-04-20 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0006_alter_tarefa_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='status',
            field=models.CharField(choices=[('EM_ANDAMENTO', 'Em andamento'), ('CONCLUIDA', 'Concluida'), ('ABERTA', 'Aberta'), ('CANCELADA', 'Cancelada')], default='ABERTA', max_length=20),
        ),
    ]
