# Generated by Django 6.0.3 on 2026-05-26 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0007_alter_tarefa_prioridade_alter_tarefa_status'),
        ('tarefas', '0007_alter_tarefa_status'),
    ]

    operations = [
    ]
