# Generated by Django 6.0.4 on 2026-04-20 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0007_alter_tarefa_prioridade_alter_tarefa_status'),
        ('tarefas', '0007_alter_tarefa_status'),
    ]

    operations = [
    ]
