<<<<<<< HEAD
# Generated by Django 6.0.3 on 2026-05-26 20:43
=======
# Generated by Django 6.0.4 on 2026-04-20 23:12
>>>>>>> 6963cd2023785647491a85d84e7e9d5d6e64e2f1

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        ('tarefas', '0008_merge_20260526_1739'),
=======
        ('tarefas', '0008_merge_20260420_1932'),
>>>>>>> 6963cd2023785647491a85d84e7e9d5d6e64e2f1
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='usuario_responsavel',
<<<<<<< HEAD
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.usuario'),
=======
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.usuario'),
>>>>>>> 6963cd2023785647491a85d84e7e9d5d6e64e2f1
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='prioridade',
<<<<<<< HEAD
            field=models.CharField(choices=[('URGENTE', 'Urgente'), ('NAO_URGENTE', 'Não urgente')], max_length=20),
=======
            field=models.CharField(choices=[('NAO_URGENTE', 'Não urgente'), ('URGENTE', 'Urgente')], default='NAO_URGENTE', max_length=40),
>>>>>>> 6963cd2023785647491a85d84e7e9d5d6e64e2f1
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='status',
<<<<<<< HEAD
            field=models.CharField(choices=[('ABERTA', 'Aberta'), ('EM_ANDAMENTO', 'Em andamento'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada')], default='ABERTA', max_length=20),
=======
            field=models.CharField(choices=[('EM_ANDAMENTO', 'Em andamento'), ('ABERTA', 'Aberta'), ('CANCELADA', 'Cancelada'), ('CONCLUIDA', 'Concluida')], default='ABERTA', max_length=20),
>>>>>>> 6963cd2023785647491a85d84e7e9d5d6e64e2f1
        ),
    ]
