# Generated by Django 6.0.4 on 2026-04-20 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0008_merge_20260420_1932'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='usuario_responsavel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.usuario'),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='prioridade',
            field=models.CharField(choices=[('NAO_URGENTE', 'Não urgente'), ('URGENTE', 'Urgente')], default='NAO_URGENTE', max_length=40),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='status',
            field=models.CharField(choices=[('EM_ANDAMENTO', 'Em andamento'), ('ABERTA', 'Aberta'), ('CANCELADA', 'Cancelada'), ('CONCLUIDA', 'Concluida')], default='ABERTA', max_length=20),
        ),
    ]
