# Generated by Django 6.0.4 on 2026-04-20 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0009_tarefa_usuario_responsavel_alter_tarefa_prioridade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='prioridade',
            field=models.CharField(choices=[('URGENTE', 'Urgente'), ('NAO_URGENTE', 'Não urgente')], default='NAO_URGENTE', max_length=40),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='status',
            field=models.CharField(choices=[('CANCELADA', 'Cancelada'), ('ABERTA', 'Aberta'), ('EM_ANDAMENTO', 'Em andamento'), ('CONCLUIDA', 'Concluida')], default='ABERTA', max_length=20),
        ),
    ]
