# Generated by Django 6.0.3 on 2026-05-26 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0008_merge_20260526_1739'),
        ('tarefas', '0010_alter_tarefa_prioridade_alter_tarefa_status'),
    ]

    operations = [
    ]
