<<<<<<< HEAD
=======
# Generated by Django 6.0.4 on 2026-04-20 23:12

>>>>>>> 6963cd2023785647491a85d84e7e9d5d6e64e2f1
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('nome', models.CharField(max_length=255)),
=======
                ('nome', models.CharField(max_length=100)),
>>>>>>> 6963cd2023785647491a85d84e7e9d5d6e64e2f1
                ('email', models.EmailField(max_length=254, unique=True)),
                ('ativo', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
<<<<<<< HEAD
    ]
=======
    ]
>>>>>>> 6963cd2023785647491a85d84e7e9d5d6e64e2f1
